### ISSUE TITLE
Watch for value changes, trigger autogrow

### ISSUE THREAD

**Issue by jareko999** [wrabit/vue-textarea-autogrow-directive#16]
https://user-images.githubusercontent.com/13771384/149668121-d7e24d66-ec93-44d5-adf4-672196984690.mov

First, thanks for making this, it's made things so much easier for me 👍 . 

Second, this is probably more about Vue than `v-autogrow`, but I'm having trouble. I can't use `:key="item"`in a `v-for` because it throws a bunch of warnings about detecting duplicate keys when I try to rearrange items in an array. However, this is the only way I can rearrange an array **and** the dom itself, so technically this works, but its throwing warnings every time I rearrange the list. I'm rearranging the dom using:

```
var element = this.blueprint.track[fromIndex];

this.blueprint.track.splice(fromIndex, 1);
this.blueprint.track.splice(toIndex, 0, element);
```

...But that doesn't rearrange the DOM itself, only moving the data. Again, `:key="item"` does work, but I get a bunch of warnings. 

In order for me to use `:key="item.key"` in my `v-for` (which is what normally use), I need to "watch" or somehow trigger `v-autogrow` in specific elements, is there an easy way to do something like this? Triggering a directive from a vue component?

Heres what I imagine:

```
updateArray()
// Then
this.$refs.description[index].$directive.trigger('v-autogrow')
```

How would I do this?

Or is there a better way to do this? 

Here is my component using `v-autogrow`:

```
<script>
import { TextareaAutogrowDirective } from 'vue-textarea-autogrow-directive'

export default {
  directives: {
   'autogrow': TextareaAutogrowDirective
  },
  inheritAttrs: true,
  props: {
    name: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: false,
    },
    value: {
      type: String,
    },
  },
  computed: {
    currentValue: {
      get() {
        return this.value;
      },
      set(val) {
        this.$emit("input", val);
      },
    },
  },
};
</script>

<template>
  <div class="textarea">
    <label :for="name">{{ label }}</label>
    <textarea
      :name="name"
      v-model="currentValue"
      v-bind="$attrs"
      ref="input"
      v-on:input="$emit('input', $event.target.value)"
      v-autogrow
    />
  </div>
</template>
```

**Comment by wrabit** [comment]
I'm sorry for the delay in responding. Did you manage to resolve this?

**Comment by jareko999** [comment]
Yes, resolved. Was unrelated, thanks!
